### ISSUE TITLE
Manual sorting broken after note changes

### ISSUE THREAD

**Issue by brettz9** [HappenApps/Quiver#1025]
If I have manual sorting, adding a new note or deleting a note, causes the latest manual sorting order to be broken.

**Comment by TheFriendlyCoder** [comment]
I just recently purchased Quiver, and one thing I'd like to do is sort my notes by "priority" to be able to construct simple todo-lists for myself and manual sorting is essential to this workflow. This is an important feature for me so if this could be fixed sooner rather than later I would greatly appreciate it.

**Comment by ylian** [comment]
Fixed in 3.1.2.
