### ISSUE TITLE
Where did my shared library GO??

### ISSUE THREAD

**Issue by rocketlaura** [HappenApps/Quiver#1050]
I've been using Quiver for a few years now, and putting everything I have into it. I use Dropbox for syncing, so I have put my main library in my Dropbox folder. No problems at all until today. Today, I launched Quiver and -- ta da! there IS no library. I go to preferences and tell it to use the library in Dropbox, and the library shows up as EMPTY. 

So ... here's what happened, I think. For some reason, when I launched Quiver, it couldn't find the file on Dropbox ... so it just created a brand-new, empty one. I haven't moved or changed anything in my Dropbox folder, so I don't know what's up there. I finally found a "qvnotebook" file in the Dropbox folder (elsewhere in my Dropbox folder) that has everything in it, which I can open as a shared file. It's not officially a library (not "qvlibrary"), so I can't set it as my library, but at least I can get at my notes.

**Comment by ylian** [comment]
That's quite strange. I am aware that sometimes Quiver failed to open the library file due to sandbox issues, but it should never delete or move the library file without explicit user action.

It might be helpful to go to Dropbox's website and go to "Files", then "Deleted Files". If the library file was indeed deleted, it should show up there.

**Comment by ylian** [comment]
Please try this build: https://www.dropbox.com/s/8ha3fg50rz0yit9/Quiver%203.1.3%20Beta.zip?dl=0

I fixed an exception that could occur during the app launch.

**Comment by ylian** [comment]
Fixed in 3.1.3. In previous versions an exception might be thrown during the app launch, which make the library show up empty.
