### ISSUE TITLE
[Feature Request] Enable Native Tab Support

### ISSUE THREAD

**Issue by dennishylau** [HappenApps/Quiver#1054]
Currently only new window is supported. Tab support will be very useful, thank you!

**Comment by preflight** [comment]
Quiver 3.2.3 supports native tabs in Mojave when opening individual notes. Double clicking a note opens it in a new tab in a docked window when 1+ notes are already opened. @dennishylau - is this the feature you're requesting or do you mean tabbed navigation within the main app window?

@ylian - Is there an option to always open notes in a new window rather than in a new tab? The behavior doesn't appear to be controlled by the user setting at System Preferences > Dock > Prefer tabs when opening documents.

**Comment by ylian** [comment]
@preflight Yes, I changed the behavior in 3.2.3 to open notes in tabs. I will add a setting or figure out how to make it work with "System Preferences > Dock > Prefer tabs".
