### ISSUE TITLE
Notes "lost" after recent update

### ISSUE THREAD

**Issue by amyschremp** [HappenApps/Quiver#1124]
I use "lost" in quotes because I can still see that my notes are there when I SEARCH for them... But in the Notebooks pane it shows I have no notes. Only some of my notes will open with the search function. I have a semester worth of notes on this app and can't afford to lose them.

**Comment by kdekooter** [comment]
Same problem here. A ton of business critical information is now inaccessible!

**Comment by ylian** [comment]
3.1.3 was supposed to solve this issue, but apparently it's still there. One thing I am sure is that this is due to an exception thrown during the app startup. Your notes are intact.

To get around the issue, try the following:
1. Find your library location (Preferences > Sync > Library Location), **BACK IT UP** by making a copy of the .qvlibrary file. All your notes are in there, so better safe than sorry.
2. Now delete the application support directory (~/Library/Containers/com.happenapps.Quiver). Delete and reinstall the app.
3. Open the app and restore from your backup (Preferences > Backup > Restore from Backup...)

**Comment by GaryBoone** [comment]
Wow. This is really broken.

After rebooting my machine, I found that all my notes were gone. The only notes in Quiver were the tutorial. The Quiver.qvlibrary file in ~/Library/Containers/com.happenapps.Quiver was only 559K in size, too small to contain my notes. Sure enough, following the procedure above had no effect.

I then restored from a months-old backup. Now, instead of seeing months-old data, I saw all of my notes including up to the most recent from yesterday. That's a relief; I haven't lost any data. Now I see that Quiver.qvlibrary file in ~/Library/Containers/com.happenapps.Quiver is 16.8M.

But what a mess!  If the current Quiver.qvlibrary file in ~/Library/Containers/com.happenapps.Quiver contains the live data, then why didn't the previous one, which was only 559K? Or is the backup the live data, since importing it restored the latest data? But then what do I back up? If I make another backup from within the program, will that overwrite my live data? Is this program and my data in a stable, reliable state?

**Comment by ylian** [comment]
@GaryBoone Looks like your "backup" is actually the live data. The current backup/move options are a bit confusing. You probably moved the library instead of creating a backup. I will simplify these options.

**Comment by GaryBoone** [comment]
Thanks, Yaogang. That makes sense of it. 

I notice that the "backup" Quiver.qvlibrary file and the one in ~/Library/Containers/com.happenapps.Quiver both have months-old timestamps for file creation and file modification. So even though one was current, there was no way to tell which one was the current one from the file info reported in Finder.

It also means that nor can I tell right now which file is currently updating as I save additional notes. 

Now that I see all of the notes again, I can keep working. But what state am I in now that I've restored a moved library? The Sync | Library Location currently points to ~/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary. Is that being updated or is Quiver still saving to the moved library?

Maybe the problem is simply that when you move a library, Sync | Library Location doesn't update to point to the current, moved location?

**Comment by ylian** [comment]
@GaryBoone The "Sync | Library" location is where the live data is. So right now it's pointing to the default location (~/Library/Containers/com.happenapps.Quiver/Data/Library/Application Support/Quiver/Quiver.qvlibrary).

When moving a library, the "Sync | Library" location should update to the new location. I will check if there are edge cases where this does not work properly.

Also to answer your earlier question, the easiest way to back up is simply make a copy of the live data (Quiver.qvlibrary). The backup functionality inside the app does nothing more than that, and I should probably remove that option or make it automatic.
