### ISSUE TITLE
URGENT Repeatedly losing data

### ISSUE THREAD

**Issue by adamjgrant** [HappenApps/Quiver#1189]
This has happened three times in the last week. I've been staying up late working on homework on one computer, only to find when switching to another computer, my work is gone. Back on the other computer it's gone too.

My assumption is this is due to Quiver using a file for all notes instead of CloudKit. If I make a change on Computer 2 before it has received changes from Computer 1, it prefers the changes of 2 thus discarding the changes from 1.

Is there any way I can retrieve the conflicting files? My homework is due and Quiver has thrown it away.

**Comment by ylian** [comment]
Yes, Quiver relies on the cloud service to sync the Quiver library. iCloud Drive syncs Quiver.qvlibrary as a single file package, so conflicting changes could overwrite the previous ones.

I am afraid you can't find the conflicting files from iCloud Drive since it's already overwritten. If you have another backup option such as a Time Machine setup, you can find the previous versions in there.

**Comment by adamjgrant** [comment]
@ylian It looks like I've lost the work I've done from staying up until 3am.

I didn't hear in your previous comment about next steps on your side to correct the issue or warn users about this very serious outcome. Can you elaborate?

**Comment by ylian** [comment]
Sorry to hear that. The app should have at least warned the user of the conflict.

This issue is one of the reasons I decided to rewrite the model layer and syncing code in the coming update (Quiver 3.2). The new version addresses this issue by detecting the changes and reload the note before new edits. This should fix the problem you had. I am trying hard to finish up this update and it's days away from release.

**Comment by duskalbatross** [comment]
Sorry, but I met the same issue last night. I lost a document which I work on for the whole day. Hope it can be fixed in the new version.

**Comment by adamjgrant** [comment]
@duskalbatross Sorry to hear that. As a defensive strategy, you may want to create new notes any time you switch computers. It appears the quiver library is not synced as a single entity, but as individual pieces (notes) in the package. In the event your changes haven't propagated to the machine you continue working on, as long as you start your work there in a new note, there shouldn't be any sync conflict.

**Comment by olibclarke** [comment]
Hi @ylian any ETA on the update? This thread makes me concerned about using Quiver for recording important data...

> Sorry to hear that. The app should have at least warned the user of the conflict.
> 
> This issue is one of the reasons I decided to rewrite the model layer and syncing code in the coming update (Quiver 3.2). The new version addresses this issue by detecting the changes and reload the note before new edits. This should fix the problem you had. I am trying hard to finish up this update and it's days away from release.

**Comment by ylian** [comment]
@olibclarke Submitting this weekend.

**Comment by matchavez** [comment]
That's good news. Not using the app until data loss is sorted.

**Comment by ylian** [comment]
Quiver 3.2 is just released. Syncing has been completely revamped in this version. File watching is now turned on for iCloud Drive, so the app now automatically detects changes and reload the notes.

**Comment by adamjgrant** [comment]
Thank you @ylian  This is working much better now!
