### ISSUE TITLE
[Suggestion] Dark Theme should apply to entire interface

### ISSUE THREAD

**Issue by mikattack** [HappenApps/Quiver#137]
The included Dark Theme seems to miss several areas of the UI:
- Search bar
- Notebook notes listing
- Note metadata (tags, created/updated, buttons)

The editing area is very customizable, but there are several items that are unclear how to target via CSS.  In particular the **Note Title**.  Is there a way to "inspect" elements?  Or better, just a list of all possible elements?

This is an excellent application, but I need all parts of it dark to use it without hurting my eyes (yeah, I'm one of those people).

**Comment by ylian** [comment]
I may add another theme for that - an all-dark theme. Some users like the current dark theme.

**Comment by techpeace** [comment]
:+1: I was just headed this way to request the same thing. Thanks!

**Comment by michaelnew** [comment]
Just wanted to cast a vote for this as well. It was very first thing I tried to change after downloading the app.

@mikattack looks like `#titlearea input { color:white; }` is how you get at the note title. If you look in `Quiver.app/Contents/Resources/HTML/css` you can see the bundled css files and find out what's-what.

@ylian It would be really great if we could just do our own custom css themes for the entire app. Seems like it's halfway there already with the css for the different cell types. You know how programmers are with their colors :)

**Comment by ylian** [comment]
The new dark theme is coming in the next update. Public beta any day now.

I know everybody would like to customize the color schemes, but each theme actually contains about two dozen color variations. There are way more details than most users care about or think about. For example, the selected state of a button, the highlighted state of a table row, slightly different colors in a popover, etc.

Hopefully the new dark theme will make most users happy.

![screen shot 2015-09-03 at 6 55 13 am](https://cloud.githubusercontent.com/assets/984895/9656741/c05fb67e-5208-11e5-932c-b727a01fc530.png)

![screen shot 2015-09-03 at 6 55 35 am](https://cloud.githubusercontent.com/assets/984895/9656743/cd712758-5208-11e5-8a9a-11e1a180dcd4.png)

![screen shot 2015-09-03 at 6 56 06 am](https://cloud.githubusercontent.com/assets/984895/9656761/e274f198-5208-11e5-98e5-286cd877f164.png)

![screen shot 2015-09-03 at 6 57 52 am](https://cloud.githubusercontent.com/assets/984895/9656792/2563a9fe-5209-11e5-96b6-328dc2599d3f.png)

**Comment by michaelnew** [comment]
@ylian that looks excellent, thanks for the quick response. I understand what you're saying about the several dozen different values that would go into a custom color scheme. I think what I'm really after is just something like this:
![screenshot 2015-09-06 17 22 57](https://cloud.githubusercontent.com/assets/522101/9707393/f0e367f4-54bb-11e5-950f-a5eae8688b2e.png)

Basically just changing the background and title colors of the main area to match the color of the cells, so it's just a seamless background, rather than the oddly-contrasted cells.

I was able to change the colors to my liking by editing `common.css`, but obviously that's going to get wiped out whenever I update the app. Maybe a good middle ground would be to expose `common.css` in the settings->styles panel, that way they could be edited by anyone who wanted to, and not in the hacky way that I did it.

**Comment by ylian** [comment]
@mikenew12 I see. You can put the CSS changes in the editor CSS (Preferences > Styles > Editor), and that takes precedence over "common.css".

But I think many other users actually want the whole UI to be dark, including the note list, tag field, format bar, find bar, search field. The screenshots are what's to come.

**Comment by ylian** [comment]
Fixed in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by ylian** [comment]
Custom themes are now implemented in Quiver 3.0 beta 7: https://github.com/HappenApps/Quiver/issues/162#issuecomment-146701280

You can customize over 200 UI details.
