### ISSUE TITLE
A way to track progress?

### ISSUE THREAD

**Issue by donifer** [HappenApps/Quiver#1380]
Is there a way we can track progress on what's being worked? I really like Quiver and will continue to support you but I would love to see some improvement on developer <-> user communication.

All we have is this issue board and an inactive twitter account. According to the issues tons of thing are in-progress and being released on the next version which is coming soon ™️.  However, that was said with the iOS app for quite a while now (1+ years).

Some of us are waiting for some of these issues to get resolved and it would be super useful to be able to track the progress. For example, I'm not sure if I should look for an alternative with better iOS sync support or just wait for the next release. I really want to just wait but it's pretty annoying just not knowing anything at all of whats going on 🤔 .

I understand that deadlines are sometimes impossible to meet, and "When it's ready" is the best approach, but maybe some kind of updates of whats been done and what not?

I'm honestly not sure whats the best approach to solve this, would love to hear your thoughts.

Thanks for all.

**Comment by ylian** [comment]
Yes I am aware of the lack of communication. I admit it's an issue but it also gave me the quiet time that I really needed to finish things. In the past year I have been working non-stop to tackle some really big pieces --- basically all the major pieces left to bring Quiver to its full potential.

I think I have mentioned this in other tickets, but here are the three major projects I have been working on:
1. A major rewrite of the macOS app. This involves basically rewriting everything other than the model layer (which was already rewritten in Quiver 3.2). This major rewrite is needed for several reasons: 
(1) Objective-C code needs to be converted to Swift (DONE already). 
(2) Old imperative UI approach needs to be replaced with a declarative approach (DONE already). 
(3) UI enhancements (sectioned note list, TOC, etc.) (Work in progress). 
(4) Bring Quiver to other platforms (foundation is laid for Linux and Windows, will tackle after Quiver 4.0 for macOS is released).
2. A complete rewrite of the iOS app. There are also a few things here: 
(1) Convert all Objective-C code to Swift (DONE already)
(2) Convert the old imperative UI approach to a declarative approach (DONE already).
(3) Adding more syncing options (work in progress)
(4) Editing support (work in progress)
3. Building a new code editor and a Markdown editor from the ground up. This is needed for editing support in the iOS app (since Ace doesn't work on mobile), as well as fixing long-standing issues with Ace. This involves:
(1) A new lossless Markdown parser (DONE)
(2) A new code editor/Markdown editor (80% done)

That's the status of things.

**Comment by donifer** [comment]
This is exactly what I needed to hear, thank you so much! What do you think about having a `Progress` pinned issue with basically your comment and block all comments?

Just so we can have one place to go and check for updates instead of lurking through all of the issues?

Side-note: Since you won't be using Ace anymore, does that mean we will lose `vim` keybindings? 😢

**Comment by ylian** [comment]
@donifer That's actually a great idea. I will do that.

No, you won't lose vim bindings. I am deeply aware the importance of vim bindings to some users, and I have already spent two weeks porting the vim bindings. That is around 50% done.

**Comment by donifer** [comment]
Awesome! Thank you so much! Closing as this has no action items, will subscribe to the pinned issue when ready. 💯

**Comment by ylian** [comment]
@donifer Created a "progress report" issue (#1381) and pinned on top. Thanks for the suggestion!

**Comment by wizyoung** [comment]
I have been using quiver in the past two years. Especially in this job-hunting summer I used quiver to organized all my notes. I feel deeply appreciated for the author's hard work and understand the workload. And I feel excited about the progress report!
