### ISSUE TITLE
Preserve formatting/infer markup when changing between cell types

### ISSUE THREAD

**Issue by nschneid** [HappenApps/Quiver#14]
Don't know how easy this would be to implement, but it would be nice if the following were supported:

- Recognize URLs when changing a cell from Code, Markdown, or LaTeX to Text.
- Actually convert formatting when changing a cell between Text and Markdown. I.e.:
  * When converting a Text cell to Markdown, add the appropriate markup where there is formatting. E.g., heading text should be prefixed with `#` characters.
  * When converting a Markdown cell to Text, actually render it in the cell so formatting is preserved.

**Comment by ylian** [comment]
Some conversions have to be lossy, such as from text to Markdown. None of the text-to-Markdown converter works reliably. It's better to avoid the whole thing altogether. (In Quiver 1.0, I was actually thinking about having a single text/Markdown cell type, but scraped that because those conversions aren't reliable.)

**Comment by ylian** [comment]
Also, some operations you mentioned are not lossy, e.g., converting a Markdown cell to text. The problem is when you convert it back to Markdown. Ideally "operation \* reverse operation = Identity". But because one step is lossy, the whole thing just blows up. Keeping text-only during the conversions is the closest I can get to achieve "operation \* reverse operation = Identity".

**Comment by nschneid** [comment]
Isn't it the case that Markdown allows HTML markup, so anything that can be formatted in text mode can also be formatted in Markdown (but not always uniquely—multiple ways to indicate italics, etc.—and sometimes requiring HTML)?

**Comment by ylian** [comment]
HTML is dirty. Missing tags and everything. That's why conversion isn't reliable.

**Comment by ylian** [comment]
Reopen this now that I have a good HTML to Markdown converter. #95

**Comment by ylian** [comment]
Now that I am revisiting this issue, my opinion on this has changed. I think it's okay to be lossy when converting HTML to Markdown. That's what users expect anyway --- HTML is messy, Markdown is neat, so it's expected to lose some data (not text content, just tags stuff) during conversion.

So the goal for such a converter is not to reproduce the original HTML perfectly with Markdown, but to clean up the original HTML, while keeping important data such as text content, basic formatting.

**Comment by ylian** [comment]
Implemented in 2.2b25:

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b25.zip

When converting a Markdown cell to a text cell, Quiver now renders it into HTML. When converting a text cell into Markdown, Quiver now use unmarked to convert HTML to Markdown.

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
