### ISSUE TITLE
(v3) Sequence diagram parsing error

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#174]
![2015-09-10 22-50-41](https://cloud.githubusercontent.com/assets/697301/9800650/77ff8fe2-580e-11e5-9168-25d9f8ba2536.png)

![quiver 2015-09-10 22-51-48](https://cloud.githubusercontent.com/assets/697301/9800670/993053b8-580e-11e5-92fc-a671368f0a99.png)

```
participant Client
participant Server

Client->>Server: ping
Note right of Server: Thinking...
Server->>Client: pong
Note left of Client: Parsing...

loop desc
    Client->>Server: aaa
end
```

**Comment by ylian** [comment]
Quiver 3.0 uses https://bramp.github.io/js-sequence-diagrams/ for the sequence diagram, not Mermaid. I am not familiar with these syntaxes. Is Mermaid syntax mostly a superset of https://bramp.github.io/js-sequence-diagrams/?

**Comment by Strajk** [comment]
Oh, I haven't found any documentation of sequence diagram in Quiver so I googled something like "sequence diagram markdown like syntax" and first result was Mermaid, syntax worked so I thought it's Mermaid :)

**Comment by Strajk** [comment]
Feel free to close this issue then :+1:

**Comment by Strajk** [comment]
Maybe in the future :) https://github.com/bramp/js-sequence-diagrams/issues/41

**Comment by ylian** [comment]
Yep, good thing that Mermaid's sequence diagram syntax is based on https://bramp.github.io/js-sequence-diagrams/. Mermaid is still early in development. Its dependency on d3.js makes it too heavy to include in Quiver. It should be possible to get rid of the d3.js dependency and generate SVG directly, since we are only dealing with primitive shapes here. I might work on it some day.
