### ISSUE TITLE
Notebooks broken

### ISSUE THREAD

**Issue by macaaw** [HappenApps/Quiver#186]
I have quite a few notes that are on my iCloud drive, but they seem to have been lost from my Quiver notebook. If I try to Open another Library and point it at the iCloud location of notes then it just tries to drill through all the folder

![screen shot 2015-09-19 at 07 38 56](https://cloud.githubusercontent.com/assets/409550/9974963/b572bfae-5ea1-11e5-9d19-b73b188b2dd2.png)

![screen shot 2015-09-19 at 07 39 36](https://cloud.githubusercontent.com/assets/409550/9974964/b8c4911e-5ea1-11e5-9550-f04e20b64876.png)

![screen shot 2015-09-19 at 07 39 43](https://cloud.githubusercontent.com/assets/409550/9974965/bbd6e08c-5ea1-11e5-82cd-6e6e843539f3.png)

![screen shot 2015-09-19 at 07 39 58](https://cloud.githubusercontent.com/assets/409550/9974966/c041148a-5ea1-11e5-8311-81952b18e5cd.png)

![screen shot 2015-09-19 at 07 40 03](https://cloud.githubusercontent.com/assets/409550/9974971/c50e3d94-5ea1-11e5-947f-a8d6a86147b7.png)

Can I recover from here?

**Comment by ylian** [comment]
iCloud Drive sometimes mistakenly change "Quiver.qvlibrary" bundle into a regular folder. I suspect this happens when you click on it from an iOS device, but I'm not sure.

To fix this, on your Mac, open the iCloud Drive folder. Try to rename "Quiver.qvlibrary". I think iCloud Drive has changed it to "Quiver.qvlibrary.folder" or something like that, so you need to change it back to "Quiver.qvlibrary".

I'm not entirely sure if you need to do the same to ".qvnotebook" and '.qvnote". Check their names. It would be a pain if you have to rename all of them but I don't know a better way at the moment.

**Comment by macaaw** [comment]
Thank you that fixed it.

Andrew

**Comment by ylian** [comment]
If you ever figured out how this was triggered in the first place (what action causes iCloud Drive to rename the files), please let me know. That would be of great help to me.
