### ISSUE TITLE
Use system controls

### ISSUE THREAD

**Issue by auduchinok** [HappenApps/Quiver#203]
The only thing that I don't like about the app now — is js-like controls instead of look-like-system buttons, text fields, etc.

**Comment by ylian** [comment]
This is the direction Apple is going --- flat design, focus on content. Quiver's controls (buttons, segmented control) look almost the same as those on iOS (since iOS 7). For example, buttons on iOS 7+ use a simple one-pixel-wide line shape, colored to indicate it's a button. OS X is quickly moving towards this direction as well. Most controls on Yosemite and El Capitan are already very flat and simple.

**Comment by auduchinok** [comment]
Yes, they do use flat design it on iOS, but i'm talking about OS X app and it's design.
OS X isn't moving to flattening everything since Yosemite release anymore, and controls in El Capitan have even a bit more gradient/shadows than it was in 10.10.
It's not about how flat or simple buttons are, it's just about using system controls which Apple provides and almost every app use instead of drawing alien looking ones which always feel strange.
![screen shot 2015-10-19 at 20 40 07](https://cloud.githubusercontent.com/assets/3923587/10585853/09a4b542-76a2-11e5-8108-bc774a08c7de.png)
![screen shot 2015-10-19 at 20 40 26](https://cloud.githubusercontent.com/assets/3923587/10585849/0755fa80-76a2-11e5-82f7-475a56ab410c.png)

**Comment by ylian** [comment]
I see. Point taken. These are system controls but I did customize their looks quite a bit.

**Comment by ylian** [comment]
Closing this since I don't plan to change the design at the moment.
