### ISSUE TITLE
Softwrap issue when text contains CJK characters 

### ISSUE THREAD

**Issue by yohasebe** [HappenApps/Quiver#322]
Text is not wrapped correctly at the right edge of the cell when the text contains CJK characters and white spaces. As I see it, strings of CJK characters are considered as (long) words, only separated from each other by occasional white spaces.  Please take a look at the animated gif.

![cjk-textwrap](https://cloud.githubusercontent.com/assets/18207/11948061/b826c938-a8b2-11e5-8056-3243ec79d3aa.gif)

**Comment by kazec** [comment]
+1 for that continuous CJK characters are considered as a single word, so that the `jump between words` shortcut `⌥ ←` and `⌥→` is actually not functioning correctly. It's a bit weird since the native `NSTextView` has already implemented these features for free.

PS: And the  shortcut `control ←` `control →` is not working at all (for both CJK or non-CJK), which works the same as `cmd ←` `cmd →` in most text editor fields on OSX.

**Comment by kazec** [comment]
I just found out that this has been already fixed in 3.0.2. Maybe this issue can be closed now? @yohasebe @ylian

**Comment by yohasebe** [comment]
Sounds OK to me. CJK text looks fine in text cells.  

It would be nicer if it looked as good in cells of other types especially in markdown cells, though.

**Comment by kazec** [comment]
Yes, and I believe that is associated with #432 .

**Comment by yohasebe** [comment]
All right, then. Let's close the issue.
