### ISSUE TITLE
Focus lost when switching from Preview to Editor

### ISSUE THREAD

**Issue by crispinb** [HappenApps/Quiver#367]
While editing a note:
- Enter Preview mode with cmd-5 
- Re-enter Edit mode with cmd-4

I would expect at this point to be back in Edit mode, ideally at the last edit location.
Actually focus seems to be lost (at least I can't tell where it is, and Escape, arrow keys etc all just get alarms).

(Tested with 3.0.1 build 71)

**Comment by acrodrig** [comment]
Plus one: When doing a quick switch to preview the document, the position of the last edit is lost.

**Comment by elbie-x** [comment]
+1 on this one (see also [Issue 29](http://github.com/HappenApps/Quiver/issues/29)). It would be very helpful to default to coming back to the position of last edit.

I suspect the people Quiver most appeals to know the ⌘-↑ keybinding to move in general to the top of a text file; since the functionality you have going uses ⌘-↑ to move to the top _of a cell_, which makes sense, perhaps ^-⌘-↑ would do it. (Then you could let the editor/preview preserve the last scroll view.) It doesn't seem like that keybinding is used elsewhere by the app (though the Shift version is)...

**Comment by ylian** [comment]
Found a fix for this. Here is a special build if anyone wants to try: https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2080.zip

**Comment by ylian** [comment]
And here is a bonus: a menu item (and keyboard shortcut) to toggle between editor/preview.

Note Menu > Toggle Editor/Preview (cmd+shift+P)

https://dl.dropboxusercontent.com/u/3445731/Quiver%203.0.2%20Build%2081.zip

**Comment by elbie-x** [comment]
Downloaded Build 81, and that new toggle is great -- but am I also supposed to see in that build retention of the edit position? If so, I haven't detected how to make that happen.

**Comment by ylian** [comment]
Yeah, the edit position is retained. Just make some edits in a cell, switch to preview then back, the edit position is retained so you can keep typing.

**Comment by elbie-x** [comment]
Ah, I see. So it's just supposed to keep the Edit and Preview windows synced? That's working like a charm!

I was thinking that I could edit a Note, go look at a wholly different Note, then come back to the first one and find my edit position preserved. But I suppose you haven't gone there (yet!).

Nice stuff.

**Comment by ylian** [comment]
@elbie-x Yeah, this ticket is just for keeping focus while switching between preview and editor. I believe there is another ticket filed for the other enhancement.

**Comment by crispinb** [comment]
This is working well for me. And the new toggle shortcut is very handy, thanks.

**Comment by ylian** [comment]
Fixed in 3.0.2.
