### ISSUE TITLE
Key Repeat w/ Vim bindings doesn't work

### ISSUE THREAD

**Issue by samullen** [HappenApps/Quiver#424]
I like the app so far, but there are a few quirks I've encountered. I primary one is that when I use Vim "key bindings" for editing cells, key repeat is turned off. Doesn't matter if I'm in insert mode or command mode, holding down the key only issues a command once. Regardless of how long the key is pressed.

I really wish there was a different binding for "Find", but I can live with it. Going to try to use this in place of nvAlt. I think I like it better, but the jury's still out. Definitely worth the $10, though. Good job.

**Comment by segphault** [comment]
The problem occurs because OS X itself hijacks the press-and-hold input event and uses it for accented character selection. What you can do to fix the issue yourself is tell the platform not to intercept the event when it occurs in Quiver. Just type this at the command line:

> defaults write com.happenapps.Quiver ApplePressAndHoldEnabled -bool false

You can always reverse it later by doing it again and substituting `false` for `true`. Fwiw, this is a common problem that comes up with Vim keybindings in OS X applications. You also have to do this if you use Vim keybindings in Atom, for example.

I'm not sure if it's possible, but It might be nice to have a checkbox in Quiver's preferences that toggles this behavior for the user without having to resort to setting it from the command line.

**Comment by samullen** [comment]
You're just all kinds of awesome. Thanks.
