### ISSUE TITLE
All Notes and Notebooks are Gone???

### ISSUE THREAD

**Issue by ghost** [HappenApps/Quiver#463]
Hi,

My entire notes and notebooks are vanished.

I only opened Quiver.

How do I restore them?

This happened a few times back, I reboot my mac it returned. but this time, notes are not getting back.

**Comment by ylian** [comment]
Check where your library is stored. If you moved it to iCloud Drive, Dropbox, Google Drive, etc., check there. Otherwise it's in the default location: `~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary`.

If you had it on iCloud Drive, make sure iCloud Drive is turned on.

Check the library used by the app by going to Preferences > Sync. The currently used library's location is shown there. If the location doesn't match where your library really is, you can choose "Open an Existing Library"  and load the correct library.

**Comment by ylian** [comment]
Also let me know which version of Quiver you're using.

**Comment by ghost** [comment]
Hi,

I have Quiver 3.0.1 (78).

The folder doesn't have the qvlibrary file. I must have moved it to somewhere.

I changed library file location yesterday after the notes got lost.

I have Time Machine on my mac, so if I can get the location of the library file in some settings file, I may be able to restore my library file.

**Comment by ylian** [comment]
Thanks. The library location in the settings file is the same as shown in the Sync panel in Preferences:

![image](https://cloud.githubusercontent.com/assets/984895/13098141/73a2c720-d4f5-11e5-9819-7c554e4d388a.png)

It's probably already reset to the default location, but check anyway.

Since your library file is not in the default location, you probably moved it to a cloud service. Check in any cloud service you use.

If still can't find it, you can try searching "Quiver.qvlibrary" in Spotlight.

**Comment by ylian** [comment]
Also, I am available for Google Hangout if you want to do that. It's usually much easier to figure out what happened with screen sharing.

**Comment by ghost** [comment]
Hi,

Thanks for your response.

I launched Time Machine and looked up for Quiver.qvlibrary.

It seems I put the file on my Dropbox and I deleted the file by mistake.

I restored the latest version of the quiver library from Time Machine but it is almost a month old.

The "accident" happened a while ago and I didn't recognize it. 

Does Quiver read library file from trash bin?

I'm going to try to fetch the deleted file from Dropbox.

I've got some important notes back!

**Comment by ylian** [comment]
Yes, Quiver uses a bookmark for the library location, so it works even if the library is moved, trashed, or renamed.

Since you had the library file in Dropbox, you can use this app to get the latest version back: https://itunes.apple.com/us/app/revisions-for-dropbox/id819348619?mt=12

**Comment by ghost** [comment]
I seems to be a good option.

Thanks!
