### ISSUE TITLE
Enhancement: Sequence Diagrams

### ISSUE THREAD

**Issue by catesandrew** [HappenApps/Quiver#47]
Enhancement: Add [sequence diagrams](http://bramp.github.io/js-sequence-diagrams/) as a note type.

**Comment by ylian** [comment]
Interesting idea.

**Comment by catesandrew** [comment]
This would be the only application that would incorporate it. Huge for programmers. And its using javascript so shouldn't be too difficult to tie into your existing framework from the looks of it.

**Comment by ylian** [comment]
Just gave this a try. It's fairly easy to integrate into Quiver. Performance is okay on desktop. But on iOS it's painfully slow (takes ~5s to render a simple diagram).

Feel free to play with it. I will decide later whether it should be put in.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b19.zip

**Comment by LeonardoGentile** [comment]
@ylian nice!
I'm following the examples at http://bramp.github.io/js-sequence-diagrams/
Two things:
- I guess isn't possible to change the sequence diagram from `hand drawn` to `simple` because this was only meant for test, right?
- Every time I want to see the result (the drawn output) should we click on the preview icon? This renders the preview of the entire note. It's not possible to have a sort of simple button or a shortcut to change the cell mode (also for markdown for example). I mean that some cell might be in edit mode while others can be in preview mode. This is because I don't find it very quick to switch the entire note to preview mode any time I want to see just how that single cell is rendered. Maybe something as in #59

**Comment by ylian** [comment]
Just tried simple. It somehow doesn't render properly. Probably some CSS issue. It is definitely faster than hand-drawn. I need to play with the library more.

For preview, a good solution is in #59. Still work in progress.

**Comment by ylian** [comment]
Performance is quite good with the "simple" option. Even on iOS. It feels lightweight and instant. I think this is promising.

Try this build. I fixed the "simple" rendering issue. A good test of speed is to keep the preview open and make changes to the diagram.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b20.zip

**Comment by LeonardoGentile** [comment]
:+1: that's not bad
If I follow your suggestion there is a little visualization issue:
- I keep the preview open
- I scroll all the way down and focus on the generated graphics 
- when editing the note (the sequence diagram) the note preview will lose its current scroll and go a little bit up so I can never be focused on the diagram while editing it

I guess this is because anytime I edit the diagram it will be removed from the preview and then added again, right?

**Comment by ylian** [comment]
That is correct. But there might be ways to get around this. I will try.

**Comment by ylian** [comment]
Both sequence diagrams and flowcharts (http://adrai.github.io/flowchart.js/) are now implemented and working well. The syncing issue will be addressed in #59.

**Comment by ylian** [comment]
Beta build 2.2b29:

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.2b29.zip

**Comment by LeonardoGentile** [comment]
On quiver 3 beta6 there is a little problem. Most probably coming from the `js-sequence-diagrams`.
If I break down an arrow description on multiple lines using `\n` as described [here](http://bramp.github.io/js-sequence-diagrams/) the description block will float over the arrow making it not visible. See the pic  
![quiver](https://cloud.githubusercontent.com/assets/412061/10335181/38c7ccc2-6cef-11e5-8213-f1eb567c86d5.png)

Also, isn't there any option to align the description text on left/right/center? It looks like it's always on the center

**Comment by LeonardoGentile** [comment]
Another bug:

```
A -> B: hello
A -> B : hello again
A -> B  : hey there
```

in these 3 case the entity `B` is assumed as 3 different entities because of the different spaces between `B` and `:`

**Comment by ylian** [comment]
@LeonardoGentile Thanks. Probably look into these a bit later. Seems to be bugs with the libraries.

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today. Copied bugs into #239.
