### ISSUE TITLE
Enhancement: Uml Diagrams

### ISSUE THREAD

**Issue by catesandrew** [HappenApps/Quiver#48]
Add [UML Diagrams](http://jumly.tmtk.net/) as a cell type. Also not sure how easy it would be to incorporate [PlantUML](http://plantuml.sourceforge.net/) if not impossible but mentioning it as it is quite popular.

**Comment by ylian** [comment]
How is this different from #47? Both are UML diagrams. Should we just choose one?

**Comment by catesandrew** [comment]
47 is just sequence diagrams which I think is easy to incorporate while this one looks more challenging if not impossible. If you are able to use plantuml then 47 is redundant, if not, then jumly looks like a good way to render uml diagrams. but I don’t think as important as sequence diagrams, just saying.

**Comment by ylian** [comment]
I see. Is PlantUML only available as in Java? I would need a JavaScript library to implement this.

**Comment by ylian** [comment]
http://jumly.tmtk.net/ seems to be lightest, but still at 56KB. js-sequence-diagrams has an easier syntax, but relies on Raphael and Underscore (another 100KB).

I will have to do some research on these UML libraries. Ideally something with a nice syntax and super lightweight.

**Comment by LeonardoGentile** [comment]
:+1: even tough https://stackedit.io/ is not a lightweight solution it has support for uml-diagram, maybe it could be a handy reference

**Comment by ylian** [comment]
@LeonardoGentile Thanks for the reference. stackedit.io seems to be using http://bramp.github.io/js-sequence-diagrams/ for sequence diagrams, and http://adrai.github.io/flowchart.js/ for flowcharts.

I integrated sequence diagrams in #47. Give it a try if you like. Performance is okay on desktop but painfully slow on iOS.

PlantUML can't be integrated because it's written in Java. Jumly uses the CoffeeScript syntax. Although I am a big CoffeeScript fan (2000 lines of CoffeeScript in Quiver source code), not everyone would appreciate that syntax in a UML diagram. So close this in favor of #47.

**Comment by LeonardoGentile** [comment]
:+1: @ylian we could still give Jumly a try just for gathering feedbacks

**Comment by LeonardoGentile** [comment]
@ylian did you take a look at https://github.com/DavidDurman/joint ?
It's quite big, not lightweight at all but it has tons of features and uses svg, maybe a custom version could fit into this project?

**Comment by ylian** [comment]
@LeonardoGentile Thanks for the reference. JointJS looks quite comprehensive. I will see if it makes sense to integrate.

**Comment by ylian** [comment]
@LeonardoGentile I don't think JointJS is a good fit for Quiver. JointJS is mostly a GUI-based diagramming library. I think a text-based diagramming library fits Quiver better, since it's simpler and basically just another variant of Quiver's code cell. That's how Markdown cells and LaTeX cells are implemented anyway.

**Comment by mshibanami** [comment]
@ylian 
* https://github.com/qjebbs/vscode-plantuml
* https://github.com/runceel/plantumlpreview

These VS Code extensions use the jar file of PlantUML on TypeScript.
Does this help you to support PlantUML?
