### ISSUE TITLE
Enhancement: Git or Github support

### ISSUE THREAD

**Issue by catesandrew** [HappenApps/Quiver#51]
Wonder how hard it would be to version notes using github as a backend or local git. Probably easier to support OAuth with Github or Gitlab service and integrate with a repo that way.

**Comment by ylian** [comment]
You can already use Git or GitHub with Quiver. That's actually how I use Quiver myself.

I check in the whole Quiver library into a Git repo, so every time I make changes to notes, I will commit the changes to Git. This way I can easily revert things back, especially handy since I often create notes for testing. You will also notice that Quiver updates the UI right away when you do `git checkout`.
