### ISSUE TITLE
Spell check in markdown not working

### ISSUE THREAD

**Issue by michaelcurry** [HappenApps/Quiver#553]
When working in Markdown, spell checker does not catch any mistakes...  I emailed in about this a while ago and was told it would be fixed soon.  What is the status of this?

**Comment by ylian** [comment]
This is difficult to fix. Basically the Ace editor (as used in Markdown cells) doesn't really support spellchecking. I have some ideas to fix this eventually but it requires major effort.

**Comment by michaelcurry** [comment]
It looks like there is an extension for ACE that does spell checking : https://github.com/ajaxorg/ace-builds/blob/master/src/ext-spellcheck.js

There is also this one (looks a little more fleshed out) https://github.com/swenson/ace_spell_check_js

I hope this helps :+1:

**Comment by ylian** [comment]
Yeah, I am aware of the plugin, but it doesn't do what you thought it would do. You need to provide autocompletion UI and dictionaries yourself, and even if you do all that, much of the standard spellchecker behavior still needs to be implemented by yourself.

For me, bundling the dictionaries is already a no-go because those dictionaries are big and non-standard. Users will be surprised to find the non-standard behaviors in the spellchecker. In my opinion the only way to do this right is to use the browser's built-in spellchecker, which means I have to swap Ace out from Markdown cell. It's certainly something I am working towards, but it will take major effort as I said earlier.

**Comment by michaelcurry** [comment]
thanks for the additional context @ylian make a lot more sense now.

**Comment by ylian** [comment]
Merge with #89.
