### ISSUE TITLE
IDEA: Name of the notebook could behave like a button to open list of notebooks

### ISSUE THREAD

**Issue by Strajk** [HappenApps/Quiver#57]
![image](https://cloud.githubusercontent.com/assets/697301/6430650/8b61ff04-c013-11e4-8bae-01ba2b880ada.png)

**Comment by Strajk** [comment]
![image](https://cloud.githubusercontent.com/assets/697301/6430655/b0a1dcbc-c013-11e4-8373-7ed9e8cfcebf.png)

**Comment by ylian** [comment]
Yep, agree. I like that feature of Evernote too.

**Comment by Strajk** [comment]
I got a feeling that Quiver is going to be big! :))

**Comment by LeonardoGentile** [comment]
While we are on this, why not a shortcut a la Evernote `Cmd-j` to jump to a notebook?

**Comment by ylian** [comment]
:+1:

**Comment by LeonardoGentile** [comment]
It seems related to #18

**Comment by preflight** [comment]
@Strajk sounds like an excellent idea, I'd find that feature very valuable

**Comment by ylian** [comment]
Implemented in Quiver 3.0 beta: https://github.com/HappenApps/Quiver/issues/162

**Comment by LeonardoGentile** [comment]
In quiver `3.0b1 (48)` there is a little problem. 
- I am on text cell 
- I hit `cmd-j` 
- I select another notebook
- The notebook is opened and the first note is shown

PROBLEM: I can't use the keyboard.  
Buy that I mean that I'm not focused inside any cell within the note. If I use the arrows I can only move the scrollbar up and down. If I hit `esc` nothing happens and I receive a noise by the os meaning I'm trying to do something not allowed.

The only way is to hit `tab`, in this case I will be focused in the title field of the note.

I would have expected to be focused on the note list of the notebook so that I can navigate beetween the notes and select the one I'm interested on.

NOTE: this seems to work if I'm already focused on a note in the note list but didn't select any cell.

**Comment by ylian** [comment]
Cool, will fix.

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
