### ISSUE TITLE
Show markdown preview when not editing

### ISSUE THREAD

**Issue by Bouke** [HappenApps/Quiver#59]
Quiver is coming along quite nicely. The markdown editing is quite welcome after struggling with Evernote. However using Markdown doesn't quite feel alright. Creating notes is only part of a notebook, reading is maybe even more important. Most notes are possibly read more often then they are edited. So to empower Markdown in Quiver I propose inline preview of Markdown blocks. If the Markdown block has focus (cursor), the current text editor is shown. Once the focus (cursor) moves to another block, the text editor is replaced with the Markdown preview of that block.

**Comment by Strajk** [comment]
But please, if decide to make this feature, make it please please set-able in preferences... My eyes got used to markdown syntax :))

But sounds like nice feature :+1:

**Comment by ylian** [comment]
I have been thinking about improving Markdown preview for a long time. And I think I have something better for 2.2.

I have tried inline Markdown preview (render a Markdown when it's not in focus), but the user experience is not good. Cells shift up and down because rendered cells have different heights from the raw Markdown cells. A key design consideration of Quiver is "edit in place", with minimal movement of the editing environment. For example, click in any cell, you see an outline of the selected cell, but the text doesn't move around at all. This is key to a great editing experience.

But coming in 2.2, each note will have three view modes: edit, preview and split view. It will be implemented as a segmented control. Like in this mockup:

![quiver-solarized-dark-theme](https://cloud.githubusercontent.com/assets/984895/6483485/c88d1a70-c23f-11e4-9385-3afaf3e259d6.png)

So you can leave the segmented control at "preview", and all your notes will be rendered. This is great for browsing.

For editing, you would use either the "edit" mode, which is the same as what you see today, or the new "split view", which turns Quiver into a standard two-column Markdown editor. Both sidebars can be hidden. Note that the mockup isn't showing the split view.

**Comment by nschneid** [comment]
Sounds like a good solution! 

I've noticed I will often start reading a note and then want to make a small edit. Maybe there should be a way to quickly toggle between Preview and Edit mode, such as double-clicking on the note?

**Comment by ylian** [comment]
I am thinking shortcuts like: Cmd+1, Cmd+2, Cmd+3 for "edit", "view", and "split view".

**Comment by Bouke** [comment]
Looks like a good alternative :+1:.

**Comment by gabriellebadie** [comment]
This looks like a great solution! shortcuts for each mode would certainly be key as well.

**Comment by ylian** [comment]
Quite a few other issues now point to this one. I will try to get something working shortly.

**Comment by ylian** [comment]
This feature is almost there. Post some screenshots:

![image](https://cloud.githubusercontent.com/assets/984895/7751941/aef2fc6c-ffaa-11e4-89b4-2b153e409124.png)

![image](https://cloud.githubusercontent.com/assets/984895/7751949/c36e372e-ffaa-11e4-9ccf-b626470f226d.png)

**Comment by ylian** [comment]
I especially like browsing notes in the preview mode from the main window:

![image](https://cloud.githubusercontent.com/assets/984895/7751989/0e20672e-ffab-11e4-8831-8059b2a82d30.png)

**Comment by catesandrew** [comment]
beta please, this looks awesome!

**Comment by ylian** [comment]
Will post a beta once it's stable. Added a couple more details to the UI. I think the new UI is now complete.

Many open issues will be addressed by this new design:
- Side-by-side preview
- Browsing notes in preview mode
- Switch between single-pane/two-pane/three-pane layouts
- Search from any note window
- Search without messing up the note list
- Notebook picker (switch notebook using the title button on top of the note list)
- Much tighter sidebar and note list, thus easier to organize and view lots of notes/notebooks
- The new sidebar paves the way for implementing nested notebook, nested tags
- "Inbox" is a nice and simple concept for quickly creating a note, then organize later. Also paves the way for web clipping.
- Recents and favorites are much more accessible now.
- The sidebar may in the future support saved queries as well.
- Filter notes in a notebook
- Sort notes differently in each notebook/tag. Possibly implement "group by" as well.
- Many more export options just a click away.
- Link to a specific section in a note -> more wiki-style navigation, TOC support also possible.

![image](https://cloud.githubusercontent.com/assets/984895/7778472/c80be0de-0099-11e5-893c-fc7312c5985e.png)

**Comment by ylian** [comment]
Another screenshot with a condensed note list:

![screen shot 2015-05-22 at 4 25 26 pm](https://cloud.githubusercontent.com/assets/984895/7779071/47bc5994-009f-11e5-8fdb-e1e0f6ca62ce.png)

**Comment by preflight** [comment]
Will split view be available for all note types? I often find myself wanting to be able to split the window vertically so that I can view two notes at once or different parts of the same note.

**Comment by ylian** [comment]
@michael-jarosik No, split view is only for side-by-side preview.

**Comment by ylian** [comment]
@michael-jarosik However, split view is available for all notes. If you only use text cells and code cells, a preview is just a read-only version of the same note. It's not that useful, but seems to solve your latter use case (view different parts of the same note).

**Comment by ylian** [comment]
Quiver 3.0 implemented side-by-side preview as an alternative solution. Released today.
