### ISSUE TITLE
HTML export not like the preview

### ISSUE THREAD

**Issue by Tekl** [HappenApps/Quiver#77]
The HTML export renders the highlighted source code very differently. It uses a different theme and the first word is not highlighted. I have AppleScript cells. In HTML (DOM) the code div sometimes hat the class "hljs sql" and sometimes "hljs cs". It seems that Quiver does not export the source code format of the code cells.

**Comment by ylian** [comment]
Good point. The exported HTML was using highlight.js to do syntax highlighting, since I wanted to keep the source code. But I think the issue you just raised outweighs other considerations: if the syntax highlighter incorrectly detects the code language, the exported HTML is pretty useless.

I just created 2.1.3b6 that uses Ace's syntax highlighter in exported HTML. It uses your selected code cell theme, and languages are guaranteed to be correctly set. Give it a try and let me know any issues.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b6.zip

**Comment by Tekl** [comment]
Hi. That's really great. Seems to work well. Thanks for the fast support.

**Comment by ylian** [comment]
The previous build had some issues with exporting a notebook. If some language modes were not already loaded, those code cells won't show up in the exported HTML files. I have corrected the issue and this new build seems to work quite well. But do let me know if you find issues. Thanks.

https://dl.dropboxusercontent.com/u/3445731/Quiver%202.1.3b7.zip

**Comment by ylian** [comment]
This is implemented in Quiver 3.0, released today.
