### ISSUE TITLE
Please Please Please Please Update!!!

### ISSUE THREAD

**Issue by rockyzhang24** [HappenApps/Quiver#785]
Nested notebook and tag are so required. Thanks.

**Comment by kimaldis** [comment]
+1

**Comment by karterotte** [comment]
+1

**Comment by YujiShen** [comment]
I emailed author about the support and update, and he said

> No need to worry. Many things are in the pipeline.

**Comment by kimaldis** [comment]
I don't want to appear harsh but he should be engaging much more with his user base. He's been pretty absent from this forum for a good while now, despite the concerns being aired here. It doesn't inspire confidence and it makes me wonder about how safe the future of this product might be. 
I really like Quiver but I can't go forward with it on the back of empty promises.

**Comment by kevanchristmas** [comment]
@kimaldis wrt this exact issue, I also emailed (beginning of February) and he said

> I am staying quiet so that I can focus more time on development. I hope to get things back on track this month. :)

Here's hoping :)

**Comment by kimaldis** [comment]
It's March, now. :-)

**Comment by ylian** [comment]
Unfortunately I'm still playing catchup. I have made many underlying changes (most in JS and Markdown) but still adding test coverage so the changes don't break the app.

**Comment by rockyzhang24** [comment]
@ylian We just wanna know whether there is an expected date for releasing a new version so that this will give us some hope and keep us staying here. Thanks.

**Comment by ylian** [comment]
@yanzhang0219 It would take some time for the nested notebook feature to be ready. What you and many others **really** want is actually a "file tree", not just a UI feature, which means the data persistence scheme needs to be changed (removal of .qvlibrary and .qvnotebook, use standard files and folders instead). It's a risky change and I will do it in phases.

The next update is a smaller update to bring Quiver development back on track. A lot of underlying changes have been made for cleaner code and better performance. And most importantly, I am determined to add full automated test coverage in this version. This is essential for further development as well as scripting support (I am using AppleScript for automated functional tests).

Things that are already done and surely will go into the next update:
* Changed the Markdown parser to markdown-it. As a result, Markdown rendering is now significantly (25x) faster, and many parser-related bugs are fixed.
* The Evernote importer now uses much less memory and can import huge (gigabytes) ENEX files. It also runs faster.
* Added support to export a note as a single image (PNG)
* Improved the PDF export functionality
* Fixed a bug that empty tags were shown in macOS Sierra.
* Changed the default font in the editor and preview to the Apple system font
* Fixed an issue that newline characters could be inserted into a note’s title
* Added a keyboard shortcut (Ctrl+Cmd+M) for “Move to Notebook”
* Fixed a bug that keyboard navigation sometimes gets stuck at the end of a cell.
* Deleting the last cell in a note will now set the focus on the second last cell so that you can keep deleting.
* Tab completion in code cells was removed as this feature was rarely used.

**Comment by rockyzhang24** [comment]
@ylian Thank you for your reply. Keep fighting. And I suggest you to post the progress and your objectives on twitter. I think many users are planning or have planed to give up this app and change to another. The post will help you bring them back.

**Comment by kimaldis** [comment]
Thanks for the update, @ylian. It really is appreciated.

I get that nested notebooks might be a big deal but right now it's killing me. But I'd really like to stay with Quiver; other than nesting it really fits the bill for me so I'm wondering if there might be some kind of interim solution that might even partially fill the gap while you work on a proper solution.

You might have some thoughts of your own on this but a couple of things popped into my head:

Additional options under the File menu; Open Existing Library and Open New Library. I can open existing libraries. I'm currently sort of half organising my notes right now by using the Open Existing option under Sync Preferences. I can also open existing Libraries by double clicking on .qvlibrary files. Options under the File Menu would just tidy the process up a little.

This one may or may not be too much work but it would be awesome. I really, really like the way Bear Notes deals with hierarchical keywords. You add keyword, say, "/Code/Javascript"  to several note and Bear maintains a collapsible  list of the structure in a column:

Code
       Javascript
       
Click on 'Javascript' and the notelist shows a list of notes containing the keyword.

It's very elegant and very useful.

Just a couple of thoughts. Adding to you already, I'd imagine, huge workload.

thanks.

**Comment by kimaldis** [comment]
One more thing; I don't really care about the underlying file structure; nested or not nested directories, it doesn't matter at all to me. All I really care about is being able to organise my notes for viewing in Quiver. On disk, it can be flat. I don't care. Look to MWeb for this.

**Comment by ylian** [comment]
@kimaldis Thanks for the suggestions. I will take a look at MWeb.

**Comment by ylian** [comment]
Just submitted 3.0.4. It should be available for download this Wednesday. Major changes are listed in the previous comment (https://github.com/HappenApps/Quiver/issues/785#issuecomment-283913832).

Although this update is relatively light in terms of new features, the JavaScript code for the editor and preview has been refactored three times (removal of jQuery, CoffeeScript -> JavaScript ES6, refactor big files into small ES6 modules). I am glad that the JS part of the codebase is finally brought up to the modern JS practices. These changes also improve the performance of editor/preview.

I have also spent lots of time setting up testing infrastructure (both unit testing and functional testing). I have found some success writing unit tests with Karma, and functional tests with AppleScript. I plan to write a lot more tests (esp. unit tests) in the near future.

There are still so many interesting ideas I want to try. I plan to push out a few more updates in the coming weeks to catch up with the backlog. I will also lay the foundation for major changes in the next several updates.

**Comment by rockyzhang24** [comment]
@ylian Great job. Thank you for your hardworking. :)

**Comment by LeonardoGentile** [comment]
@ylian finally..thanks!
Btw, how would you know that 
> Tab completion in code cells was removed as this feature was rarely used

Why removing something if it's not broken?
I don't use it everyday but from time to time it's been helpful

Nested Notebook please!!! 👍

**Comment by LeonardoGentile** [comment]
Another thing, I know and we already discussed you have been really busy but almost 1 year of silence has bothered me and many others. We are all developers here and we know things get busy but being kept in the dark is not great. This is not an open source project but you can see there is a very active community around quiver both reporting bugs and proposing new features. 

This sort of implicit collaboration should not be broken if you want us to continue support this app.

So please could you share here or somewhere else a time schedule, a timeline, a list of features, anything, even a foggy date (Ex. Summer or December 2017, ectr.) about the future of your work on this app?

Thanks for coming back 👍

**Comment by ylian** [comment]
@LeonardoGentile Sometimes it's necessary to remove certain features to move forward. :) In this case, tab completion is rarely used (no one has complained about it since the update), not very useful (snippets couldn't be customized), and non-essential (Quiver is not going to replace real code editors).

I posted about near-future plans here: https://github.com/HappenApps/Quiver/issues/803#issuecomment-288326246

I appreciate everyone's help and support, esp. during the last year. I won't delve into personal details here, but the important thing is that I have been working on Quiver on a daily basis since last Christmas. My time is still limited (if you must know, I have an unrelated day job at the moment), so I have to make some tradeoffs. I will try to be responsive on GitHub and with emails, but the priority for me is pushing out updates.

**Comment by ylian** [comment]
Closing this one.
