### ISSUE TITLE
3.0.4 Breaks linking to local files in markdown

### ISSUE THREAD

**Issue by enovid** [HappenApps/Quiver#808]
Preview is no longer rendering links that include a local file path. (See attached images)

I use this feature extensively, and it was working before the update. 

<img width="773" alt="screen shot 2017-03-24 at 9 28 02 am" src="https://cloud.githubusercontent.com/assets/8015376/24304173/b937ff82-1075-11e7-9056-49645f2ec938.png">
<img width="750" alt="screen shot 2017-03-24 at 9 28 11 am" src="https://cloud.githubusercontent.com/assets/8015376/24304174/b9f7a526-1075-11e7-8f59-a785760e51f8.png">
<img width="765" alt="screen shot 2017-03-24 at 9 28 24 am" src="https://cloud.githubusercontent.com/assets/8015376/24304172/b936d67a-1075-11e7-8970-2f95575de564.png">

**Comment by ylian** [comment]
The problem is that those URLs have spaces in them. Let me check if this should be supported or not.

**Comment by enovid** [comment]
This has always worked. And it's one of my favorite features. 

Here's how I usually add the path:

  1. Drag file into a text cell
  2. Click "Link" on popup dialogue 
  3. Convert text cell to markdown cell 

A few minutes ago, I tried escaping the spaces, and that causes the link to render, but clicking the link doesn't do anything. Clicking the link used to open the file.

**Comment by ylian** [comment]
Yes you're right. The new Markdown parser is too strict on this. I will fix right away.

**Comment by enovid** [comment]
Thank you!

**Comment by ylian** [comment]
@enovid I am addressing this issue in the next update (3.0.6), and it turns out there are several issues:

1. There is an issue with opening a local file link due to file permission errors. This might be new on 10.12.4 but I'm not sure. Anyway I have fixed it in 3.0.6.
2. URLs should not have spaces in them. When converting a file link from a text cell to Markdown, the URL should be escaped. I have fixed this in 3.0.6.

URLs should not have spaces in them, so the old parser's behaviour is wrong, and the new parser's behaviour is correct. Also, the Markdown syntax allows an extra "title" field after the url, separated by spaces (https://daringfireball.net/projects/markdown/syntax#link). Allowing spaces in URLs would break this functionality.

So the only remaining issue is backward compatibility. There are two possibilities:

1. Let the user manually fix the old links (replace space with %20). I have tested this and verified that it works (with other fixes mentioned above applied)
2. Change the new parser to allow spaces in URLs. This is hacky and the behaviour is wrong.

Would the first option be acceptable to you?

**Comment by enovid** [comment]
> Would the first option be acceptable to you?

Yes, the first option is acceptable.

**Comment by ylian** [comment]
Great, thanks. I will push out 3.0.6 with other fixes tomorrow.

**Comment by ylian** [comment]
Fixed the mentioned issues in 3.0.6. You would still need to manually replace spaces with "%20".
