### ISSUE TITLE
Composed characters broken in Markdown cells on 3.0.4 under OS X 10.12.4

### ISSUE THREAD

**Issue by geodesic** [HappenApps/Quiver#815]
Updating to macOS 10.12.4 seems to have broken the creation of composed characters in Markdown cells.  For example, to enter something like "Möbius", I would normally type:  'M', 'option-U', 'o', 'b', etc...

This worked fine previously, but now produces:

    M¨öbius

I'm not entirely sure if it was the Quiver update (3.0.4), or the macOS update (10.12.4) that broke this.  Entry of composed characters still works correctly in Text cells; it seems to be only Markdown cells that are broken.

**Comment by ylian** [comment]
I didn't change the Markdown editor in 3.0.4, so this is mostly likely due to some changes in the webview in 10.12.4. Will look into it.

**Comment by danielmunoz** [comment]
I confirm this happens when using a Spanish ISO keyboard trying to type common Spanish words like «sí».

`s´í`

This is produced by this key sequence:

<kbd>s</kbd><kbd>´</kbd><kbd>i</kbd><kbd>space</kbd> 

Obviously, you should get:

`sí `

This happens with Quiver Version 3.0.4 (96) on macOS 10.12.4 (16E195).

**Important note: this happens on all cell types except Text Cells.**

**Comment by ylian** [comment]
Fixed in 3.0.5.
