### ISSUE TITLE
Different notes in panes after moving/deleting a note

### ISSUE THREAD

**Issue by tropicoo** [HappenApps/Quiver#821]
This one is a quite old and annoying bug. After moving or deleting a note from "All Notes", index of others notes is different while viewing on panes. I've recorded two screen casts to show it:

1. Move note https://gfycat.com/ImmaterialConsiderateBlackbird
2. Delete note https://gfycat.com/WearyShockingIaerismetalmark

Quiver 3.0.5 / macOS Sierra 10.12.1

**Comment by sctice** [comment]
I've noticed this same behavior when deleting notes selected by "View" → "Jump to Notebook..." and selecting a tag.

- Create three notes with different bodies, all with a common tag, T.
- Jump to Notebook..., and select the tag T. In the three-pane view, you should see the three notes just created in the second pane.
- Delete the topmost note (I used the ⌘⌫ shortcut). Now, as you select other notes in the second pane, you'll find that their contents in the third pane don't match their summaries in the second pane.

I seem to get the same behavior when deleting notes from any collection of notes that isn't a notebook: Recents, All Notes, a tag, and so on. This bug is particularly annoying to me because I use a tag to mark notes that I'd like to delete in the near future, and then I periodically visit that tag and delete notes that are no longer relevant.

**Comment by ylian** [comment]
Will fix in the next update.

**Comment by ylian** [comment]
Fixed in 3.0.7.
