### ISSUE TITLE
Quiver not restored with timemachine

### ISSUE THREAD

**Issue by yingtho** [HappenApps/Quiver#843]
I did a full restore of my laptop but Quiver is empty when i open it.
I found a old Quiver.qvlibrary which doesn't seem to be updated since may 2016 where  i last moved the quiver library file. When i open it it was old data from back then. 
How do i restore the data now?
My quiver version 3.0.1 (78)

**Comment by ylian** [comment]
Since the library file contained only old data, it must not be the library file Quiver actually used.

In that case, I suggest looking in the default location first:

```
~/Library/Containers/com.happenapps.Quiver/Data/Library/Application\ Support/Quiver/Quiver.qvlibrary
```

This location should have been backed up by your Time Machine, so try to look in Time Machine and find this library file.

If this library file isn't the up-to-date one, then I suggest doing a full disk search for Quiver.qvlibrary:

```bash
find / -name 'Quiver.qvlibrary' -print
```

**Comment by yingtho** [comment]
You are right it was in another location. Thanks for the help.
