### ISSUE TITLE
Basic table support in text cells

### ISSUE THREAD

**Issue by ylian** [HappenApps/Quiver#85]
Currently you can create tables in a Markdown cell, but not in a text cell. Some users have discovered a workaround: create a table in a Markdown cell, open preview, copy the table from preview, then paste in a text cell.

This makes me think maybe it's enough to provide really basic table support in text cells. I definitely don't want to implement a full-fledged table widget, like the Confluence Editor. It's very powerful but also very complicated.

![tableicons](https://cloud.githubusercontent.com/assets/984895/6907432/09b4842e-d704-11e4-88ef-ef6a2b64c36f.png)

I am thinking a really basic implementation like Evernote has. Click the table icon in the toolbar, enter number of rows and columns, and a table is inserted. No fancy things like merging rows or columns.

**Comment by LeonardoGentile** [comment]
What I like of quiver is its clean user interface and basic set of features. 
Even tough this could be useful for someone I think that introducing any kind of text support would transform its clean user interface in a word-like or evernote-like monster.

I think that the main interface should only provide basic text tools, than in a separate "More.." button you could hide the less-used features/tools.

Even better the possibility to customize the toolbar..but still I would love to continue to use a very simple and clean interface

**Comment by nschneid** [comment]
Would it be possible to have a simple "insert table" button in the toolbar and put the rest of the table operations in the context menu?

**Comment by ylian** [comment]
The screenshot above is the anti-pattern. I definitely don't want to implement anything like that.

If I implement only basic table support, users would ask for more. I agree it's better to stay away from this.

**Comment by scott-mead** [comment]
I know this was closed, but, I just ran into this big time.  What I've resorted to is using sublime text + https://github.com/vkocubinsky/SublimeTableEditor to edit tables.  It's nice because it is auto-building the pipes for me and I can move between cells with tab.  It makes it very easy to enter data.  Right now, I'm exporting my spreadsheets as CSV, pasting it into sublime, converting it to a table (with the above plugin) and the moving on.  That, or, manually building a table with the sublime workflow.  Just a suggestion.
