### ISSUE TITLE
Incomplete Dropbox sync to Iphone app

### ISSUE THREAD

**Issue by kevanchristmas** [HappenApps/Quiver#920]
Wondering if there is a limit on number of notes as one notebook I have with 900+ notes only syncs with same notebook in iOS app with 150+ via dropbox?

I have refreshed, reinstalled app, reconnected and re-synced entire .qvlibrary several times - then downloaded just that notebook. Other notebooks with less notes seem to have no problem.

Quiver 3.0.7 (102)
Sierra 10.12.4
Quiver 1.0(15)
iOS 10.3.2

**Comment by ylian** [comment]
The number of notes could be an issue since there are literally 1800+ files (plus all attachments, images) to download for your 900+ notes. The initial syncing could have a hard time to complete.

Best workaround at the moment is to go into the notebook and pull down to refresh. Refreshing the notebook only downloads notes that weren't downloaded yet, thus reducing the load.

**Comment by kevanchristmas** [comment]
Thanks for the response. I had tried this (tried again after your feedback) and it doesn't seem to make any difference - no notes are added. I wonder if the fact that many of the notes have the same creation date might be affecting the transfer as well? It appears to take 

The notes are all text, and mostly short. For reference, the entire .qvnotebook file  in dropbox is only 2.8MB.

**Comment by ylian** [comment]
Then it should work. Maybe stalled at a particular note. If the note contents are not sensitive, please send the .qvnotebook to me (ylian@happenapps.com) and I will try to reproduce. Thanks.

**Comment by kevanchristmas** [comment]
Hi - have sent the notebook - look forward to hearing

**Comment by ylian** [comment]
Got it, thanks. I can reproduce the issue. Download completed but only see 150+ notes. I will figure it out and let you know.

**Comment by ylian** [comment]
@kevanchristmas Confirmed that it's due to the number of files to download. Although the files are small, downloading 1800+ files or simply checking the contents of 900+ directories caused timeout on 2/3 of HTTP connections.

For now, use several notebooks with fewer notes in each. Of course I have to address this limitation somehow.

**Comment by kevanchristmas** [comment]
Great - thanks for letting me know - I suspected as much.

I’ll try splitting them up a bit (needed to rationalise anyway)

Any idea what a safe upper limit for number of notes should be?

On 24 July 2017 at 9:32:14 AM, Yaogang Lian (notifications@github.com)
wrote:

@kevanchristmas <https://github.com/kevanchristmas> Confirmed that it's due
to the number of files to download. Although the files are small,
downloading 1800+ files or simply checking the contents of 900+ directories
caused timeout on 2/3 of HTTP connections.

For now, use several notebooks with fewer notes in each. Of course I have
to address this limitation somehow.
.

**Comment by ylian** [comment]
@kevanchristmas 200 notes should be fine.
