### ISSUE TITLE
Update to v3.1.0 has broken Popclip extension

### ISSUE THREAD

**Issue by auxbuss** [HappenApps/Quiver#980]
The Popclip extension works by passing selected text from a web browser into Quiver where it appears in Quiver's Inbox. This has stopped working. The item no longer appears in the Inbox.

However, by quitting and restarting Quiver, the entries do appear in Quiver's Inbox. 

Link to extension: https://github.com/HappenApps/Quiver/wiki/Extensions

**Comment by ylian** [comment]
Where is your Quiver library? On iCloud?

**Comment by auxbuss** [comment]
Yes.

**Comment by ylian** [comment]
@auxbuss I see. I disabled file watching on iCloud Drive. It never worked properly and the behaviour is getting much worse on High Sierra (tons of extraneous file change events for no reason).

The proper way to fix this should be through a URL scheme. Stay tuned.

**Comment by auxbuss** [comment]
I tried moving the Quiver library onto my local disk, but then the import simply doesn't happen.

Also, I noticed that the Quiver/Move Library function doesn't move the library, instead it copies it. I found this confusing.

**Comment by auxbuss** [comment]
Hi @ylian, I see that in https://github.com/HappenApps/Quiver/issues/1189 you mention that the imminent release has some improvements related to iCloud. Do you expect this issue to be fixed by these changes?

**Comment by ylian** [comment]
@auxbuss Actually yes. I re-enabled file watching on iCloud Drive in Quiver 3.2. 

Quiver 3.2 has been waiting for Apple's review for about a week, probably due to Thanksgiving. Hope Apple approves it on Monday.

**Comment by auxbuss** [comment]
Thanks for the update. Sadly, this issue isn't fixed in v3.2 (masOS 10.14.1). The symptoms are the same.

**Comment by ylian** [comment]
@auxbuss I will check. It's possible that creating a note in the inbox triggered events which are still ignored. I am only allowing a root level change event to pass through because there are simply too many file change events from iCloud Drive.

**Comment by auxbuss** [comment]
I have a little more information. When I have Quiver open on two machines, the Quiver library (Inbox) is not updated on the machine where the text is saved without reloading Quiver. However, the other machine is updated without reloading Quiver – after the library is updated on iCloud, of course.

**Comment by ylian** [comment]
Aha! That is very helpful. I mostly focused on the second case which fires a root level change event. I will check and get back to you later today.

**Comment by ylian** [comment]
@auxbuss Did some digging. Indeed, when I manually create a .qvnote file inside Inbox.qvnotebook, it fires a file change event with eventPath set to the Inbox.qvnotebook's file path.

Unfortunately I can't let this file change event through. The reason is two-folds:

1. When iCloud Drive completes syncing, it fires a flood of file change events (one file change event for every single sub directory of Quiver library), so I have to filter out these events and only process a single root level change event. Note that this is a peculiarity of iCloud Drive; no other cloud syncing service does this.
2. Within the app, I can't differentiate between file change events from iCloud daemon or third-party app like Popclip. They are both external processes.

So I can't fix this issue as it is. The right solution is to finish the web clipper I have long promised.

**Comment by auxbuss** [comment]
Okay, thanks. It's not a deal breaker given that I know the problem exists. It's not like I spend all day clipping things into Quiver via Popclip!

Coincidentally, I also use Scrivener, and I know the developer (Keith) doesn't sync to iCloud for similar reasons; a Scrivener project is also a "package" with many files, like Quiver. It might be worth contacting him to support his request for changes to Apple. Currently, Scrivener mandates DropBox for sync'ing with their iOS app for this reason. This certainly seems to be a problem of Apple's own making.

**Comment by ylian** [comment]
Quiver Web Clipper 1.0 is released: https://chrome.google.com/webstore/detail/quiver-web-clipper/hcnffmpopoelpggikahccdfenoobjigj
